### ISSUE TITLE
Add CyberKing18.me Website!

### ISSUE THREAD

**Issue by noahball** [MrCrayfish/GitWeb-Sites#10]
#banner
image=https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/serene-sunset-robert-bynum.jpg
text=&0C&1y&2b&3e&4r&5K&6i&7n&8g&91&a8&b.&cm&de

#divider
size=3
color=-3248896

#divider
size=3
color=-3248896

#paragraph
text=Welcome to the CyberKing18 GitWeb site! Here you can find information about me, and some projects I am working on, enjoy! :). Join my Discord server: https://discord.gg/YMKe4Yh

#divider
size=3
color=-3248896

#header
text=About Me

#divider
size=3
color=-3248896

#paragraph
text=CyberKing18 is a person that likes to program in: HTML, CSS, JavaScript, and Discord.js. He has programmed many Discord bots, including Horizon, RCDB Bot, Overtime, and CheeseAndCracker.fm. He is also a admin on many Discord servers.
image=https://cdn.discordapp.com/attachments/431957469153984543/431961543463403522/5822015-desktop-backgrounds.jpg

#divider
size=3
color=-3248896

#header
text=Projects

#divider
size=3
color=-3248896

#paragraph
text=Horizon is a fun & moderation Discord bot. It has many commands and is trusted by over 7840 users! you can get it by joining the Horizon Discord Server. https://discord.gg/CRtdyc6
image=https://cdn.discordapp.com/attachments/419267550459985927/449705760532987906/Horizon.png

#divider
size=3
color=-3248896

#paragraph
text=CheeseAndCracker.fm is a Discord music bot! It has a high 24/7 uptime. With songs through YouTube. It has premium auddio quality, with no fees whatsoever! You can get it in the CheeseAndCracker.fm Bot Discord server. https://discord.gg/hXK8Y6R
image=https://cdn.discordapp.com/attachments/435318824208695297/435332169737699330/CheeseAndCracker.fm-3.png

#divider
size=3
color=-3248896

#paragraph
text=I work on many more projects, these are just my priorites at the moment.

#divider
size=3
color=-3248896

#footer
title=Copyright (c) CyberKing18 2018
sub-title=Let's get in touch, Discord: CyberKing18#1289.
home-page=cyberking18.me
color=-3248896

**Comment by jacksonhardaway** [comment]
Please do not put this as an issue, but instead pull request it.
