### ISSUE TITLE
Gitweb Website Creator

### ISSUE THREAD

**Issue by EB57PzUhYmQsMm** [MrCrayfish/GitWeb-Sites#20]
When I try to use the Download button to add a download option template to download a chosen file (aka the chosen one), it crashes my minecraft.exe. No Errors. Can someone tell me the code for downloading things so I don't need that button

**Comment by jacksonhardaway** [comment]
I can't really help since I can't understand the issue at all due to the broken English.

**Comment by EB57PzUhYmQsMm** [comment]
So very sorry, you know on the git website builder app, there are templates for creating a website. If I press the "Download Button" Template and then select the file to make available for download, it crashes my Minecraft with no errors (that I know of). Can someone tell me the code for the download button so I can add it to my website 👍

**Comment by EB57PzUhYmQsMm** [comment]
Found it :)

#download
file-app=cdm.note_stash
file-data={title:"Mine Corp Cert",content:"This certificate proves that Mine Corp owns this device.\\nHave a nice day."}
file-name=Mine Corp Cert
text=Certificate of Coolness
