### ISSUE TITLE
[Feature] Subsites shouldn't need their own directories

### ISSUE THREAD

**Issue by Pugduddly** [MrCrayfish/GitWeb-Sites#21]
So, as you people may or may not know, I've been creating my own [GitWeb browser](https://gitweb-js.glitch.me/) in JavaScript. And as I was updating it to the new format, I had an idea. I don't think subsites need their own directories. You could still have nested directories and subsites in subsites, but you wouldn't have to create a directory just to contain an `index` file.
It's not hard to implement this. It certainly wasn't hard for me.
Here's how I did it in JS, if it would help with implementing it in Java.
```
function urlToUrl(url) { // Converts GitWeb URL to Github URL
    // For example, suffix.dk/sub/site => https://raw.githubusercontent.com/MrCrayfish/GitWeb-Sites/master/dk/suffix/sub/site
    var dir = url.split('/');
    var site = dir.shift().split('.');
    dir.unshift(site[0]);
    dir.unshift(site[1]);
    
    url = 'https://raw.githubusercontent.com/MrCrayfish/GitWeb-Sites/master/' + dir.join('/');
    
    // Test if file exists.
    // If not, add /index to end of url
    $.ajax({
        type: "GET",
        url: url,
        dataType: "text",
        contentType: "text/plain",
        async: false,
        error: function(data) {
            dir.push('index');
            url = 'https://raw.githubusercontent.com/MrCrayfish/GitWeb-Sites/master/' + dir.join('/');
        }
    });
  
    // We're done here.
    return url;
}
```

**Comment by MrCrayfish** [comment]
I see what you're doing but that just adds an extra request. If we have folders, it means only one request not two.
