### ISSUE TITLE
Suggestion: MineTube

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/GitWeb-Sites#23]
What if there was a website in GitWeb called MineTube? You get to record stuff with a camera (which should be a mod btw)

And then you upload it. Only people on the server can see it.

**Comment by jacksonhardaway** [comment]
Impossible.

**Comment by EB57PzUhYmQsMm** [comment]
not really impossible, the recording isn't impossible, but adding it to the website may be a challenge, kinda, images shouldn't be hard though, the video would probably be a gif file

**Comment by WeirdTreeThing** [comment]
But can gitweb play a gif
