### ISSUE TITLE
Suggestion: WebSearcher

### ISSUE THREAD

**Issue by iiisak** [MrCrayfish/GitWeb-Sites#31]
### WebSearcher
An website where you can search for other sites on the GitWeb.

**Comment by WeirdTreeThing** [comment]
I don't know how that would be possible and there is already an official site list.

**Comment by iiisak** [comment]
Maybe it can mirror the real Internet

**Comment by OstenTV** [comment]
Impossible.

**Comment by iiisak** [comment]
Why?

**Comment by OstenTV** [comment]
Because there is no way you could convert HTML into GitWeb code, and render it properly.

**Comment by iiisak** [comment]
There is an way

**Comment by iiisak** [comment]
This isn't impossible

**Comment by OstenTV** [comment]
How?

**Comment by iiisak** [comment]
An Converter?

**Comment by OstenTV** [comment]
It's not that simple. You can't just convert one language to another. Plus, getting the rendering right would be almost impossible.

**Comment by iiisak** [comment]
No it wouldn't

**Comment by iiisak** [comment]
There are bat to exe converters and more, so you can

**Comment by OstenTV** [comment]
Web rendering is a little more complicated than a batch script.
