### ISSUE TITLE
Markdown formatting?

### ISSUE THREAD

**Issue by Richienb** [MrCrayfish/GitWeb-Sites#34]
There's a library called MineDown that lets you make markdown documents Minecraft compatible. Is there any plan to support it?

**Comment by WeirdTreeThing** [comment]
Well gitweb already has formatting support. So what do you mean.

**Comment by OstenTV** [comment]
I don't know if it's possible or not (since I don't program Java), but that would actually be pretty cool.

**Comment by Richienb** [comment]
Markdown is already a known markup standard so people don't have to start learning the current format from scratch. Here is [GitHub's Version](https://guides.github.com/features/mastering-markdown/).

**Comment by Richienb** [comment]
Any update to this?

**Comment by WeirdTreeThing** [comment]
We need a developer to see this.

**Comment by jacksonhardaway** [comment]
Please out the suggestion on the Device Mod repo. The device mod is currently on a halt and wont be workes on until Cray starts working on it again. You’re already able to use bolding, colors, etc. so there is no reason for it.

**Comment by Richienb** [comment]
@JacksonPlayz In that case, I need a cheat sheet which I can use to type in this new markup language.
