### ISSUE TITLE
submit website

### ISSUE THREAD

**Issue by theyoutubermanguy** [MrCrayfish/GitWeb-Sites#38]
so i was in gitweb creator to test the code and the submit website is not working  there is a link but 404 : Page not found
![problem](https://user-images.githubusercontent.com/49345673/55671976-e7923180-5895-11e9-83f1-0dd9a8908795.PNG)

**Comment by EB57PzUhYmQsMm** [comment]
They are working on that, not at the moment though...



For what I heard

**Comment by randomised** [comment]
why dont they just add something were they can upload via github

**Comment by EB57PzUhYmQsMm** [comment]
> why dont they just add something were they can upload via github

agreed...

**Comment by theyoutubermanguy** [comment]
they should in the next version and should add a software updater and servers and a software update app
Like this so you make a server and hook it up to the laptop and installs software updater and then you can install express (all updates) or custom (choose updates) edit : meaning also you can make updates and custom apps

**Comment by EB57PzUhYmQsMm** [comment]
> they should in the next version and should add a software updater and servers and a software update app
> Like this so you make a server and hook it up to the laptop and installs software updater and then you can install express (all updates) or custom (choose updates) edit : meaning also you can make updates and custom apps

yaaaaaasss o my goodness golly I would love that!!!
It would be possible to make it an addon too and there can be an online library of addons for people to upload to and stuff can't remember much what I was thinking

**Comment by OstenTV** [comment]
You can create a site by making a pull request on GitHub. It is currently not possible in-game
