### ISSUE TITLE
Lack of features

### ISSUE THREAD

**Issue by sargedev** [MrCrayfish/GitWeb-Sites#46]
The project is still good, but feels abandoned and so does the entire mod. Please add some features like uploading files, or text fields. You could even put real code with variables and stuff, or accesing your endermail account. It's a great mod, but it's sad to see that there are no new updates. Please add some new features, I don't care what, just do something with the mod.

**Comment by JoMaZu787** [comment]
Please add a feature for uploading files!!!

**Comment by EB57PzUhYmQsMm** [comment]
> Please add a feature for uploading files!!!

I second that

**Comment by MineCraftPRO1234** [comment]
I third that

**Comment by Lelebees** [comment]
I'd love to see a feature that will allow users to create a sortof page inside a page, allowing players to share info using GitWeb without having to build a site themselves.

**Comment by EB57PzUhYmQsMm** [comment]
> I'd love to see a feature that will allow users to create a sortof page inside a page, allowing players to share info using GitWeb without having to build a site themselves.

So like a forum page? that would be great

**Comment by jacksonhardaway** [comment]
Device mod has been abandoned

**Comment by sargedev** [comment]
> Device mod has been abandoned
but why???
