### ISSUE TITLE
Suggestion: The Ability to Upload Server-Only/World-Only Websites

### ISSUE THREAD

**Issue by EB57PzUhYmQsMm** [MrCrayfish/GitWeb-Sites#48]
Since not many people upload websites and the acceptance is a high standard, then the 404 error should be fixed so that instead of submitting an official website, there should be a moderated system by the server/world owners so that friends or communities can submit funny or info websites for their minecraft server/world.

I really think this would be a good idea and would really help this mod stay alive even without a constant stream of updates like some other mrcrayfish mods (or they at least used to be highly updated, like the vehicle mod).

If you have any other additions to this suggestions then please do reply to this thread!

**Comment by jacksonhardaway** [comment]
Device mod has been abandonded

**Comment by sargedev** [comment]
but why

> Device mod has been abandonded

but why?
