### ISSUE TITLE
PixelPainter cannot open files

### ISSUE THREAD

**Issue by Ferferite** [MrCrayfish/GitWeb-Sites#7]
If i try to open a piexelpainter image(trough the File Beowser)it gives an error saying:"Pixel Painter was unable to open file".I am on the latest verison of the mod(v0.4.1)

If i try to open the same drawing trough the pixel painter browse menu,it works

**Comment by heyitsdoodler** [comment]
Why are you posting this here, please go to the Device Mod Github!
